### ISSUE TITLE
User operation timed out on upload content

### ISSUE THREAD

**Issue by enriquejosepadilla** [GoogleCloudPlatform/django-cloud-deploy#106]
User got socket.timeout: The read operation timed out. 

This is due to a network error, the user was able to get passed this by retrying the operation.

This is linked to better error messaging #79.

@brianquinlan Should we be retrying every API call atleast N times just to guarantee it wasn't "bad luck".

@wangxf123456 thoughts?

**Comment by wangxf123456** [comment]
I agree with @enriquejosepadilla. 

This can happen if the user's network connection is unstable or completely lose connection. If user's network connection is just unstable, then retrying the operation will solve the problem. This is better than throwing an error and asking users to manually retry.

If the user's network connection is completely down, we can not do anything, but retrying the operation does not make things worse.

**Comment by brianquinlan** [comment]
Do we know what operation timed out? Did the error come from `Django Deploy` or from `gcloud`.

I don't mind retry API calls that are known to fail if we know that they are idempotent.

**Comment by wangxf123456** [comment]
https://cloud.google.com/storage/docs/json_api/v1/objects/insert This api timed out. It is used to upload local files to GCS bucket.

In our code the exception was thrown on cloudlib/static_content_serve.py:179

**Comment by wangxf123456** [comment]
Fixed by #138
