### ISSUE TITLE
Project name should adhere to projectid validation

### ISSUE THREAD

**Issue by enriquejosepadilla** [GoogleCloudPlatform/django-cloud-deploy#108]
User study had an error for instance name: django-on-gke4:Django_on_GKE4-instance 

Most likely it should be lower case and no underscores. We should validate this so it doesn't cause issues.

**Comment by enriquejosepadilla** [comment]
specifically its project name causing the issue.

**Comment by enriquejosepadilla** [comment]
the error message is also unclear, Invalid Django Project name "xxx": must be a valid python identifier.

https://github.com/hashedin/django-project-template/issues/2

**Comment by brianquinlan** [comment]
The error is close to the one used by Django: https://github.com/django/django/blob/b9cf764be62e77b4777b3a75ec256f6209a57671/django/core/management/templates.py#L215

But we can come up with a better error.

**Comment by wangxf123456** [comment]
For project name, Django accepts both uppercase and lowercase characters, numbers and underscores. We already have validation for this for both "new" and update "command". (string.isidentifier())

By default we use project name for the following GCP resources:

- Database instance name: <project_name>-instance
- Database name: <project_name>-db
- 

These resource names only accept lowercase letters, numbers and hyphens. Underscores and uppercase characters are not accepted. This is why we get an error.

I suggest that  we should still allow uppercase characters and underscores for project names to be consistent with Django. For resource names, we can convert underscores to hyphens and uppercase characters to lowercase characters.
