### ISSUE TITLE
Docker Requirement confuses users.

### ISSUE THREAD

**Issue by enriquejosepadilla** [GoogleCloudPlatform/django-cloud-deploy#112]
I'm actually not sure how docker is installed for users but it gives an error when trying to use it. Double check.

**Comment by enriquejosepadilla** [comment]
https://docs.docker.com/docker-for-mac/install/#install-and-run-docker-for-mac maybe point them to that page.

**Comment by wangxf123456** [comment]
I think installing docker on Mac is completely different from Linux. 

Also, I saw one user get confused when running "sudo usermod -a -G docker $USER". This command does not exist on mac and actually this step is unnecessary on mac.

**Comment by brianquinlan** [comment]
It seems like it isn't the requirement that is confusing but how to actually do the installation?

**Comment by brianquinlan** [comment]
Maybe the "sudo usermod..." thing is only for Googlers and we should remove it.

**Comment by brianquinlan** [comment]
Also, if the user is using the App Engine flag, maybe we shouldn't require docker?

**Comment by enriquejosepadilla** [comment]
(Testing if replying creates a new comment)

Yeah thats another thing, the requirements are different, the user only
needs gcloud.
