### ISSUE TITLE
Try to install cloud_sql_proxy using gcloud

### ISSUE THREAD

**Issue by brianquinlan** [GoogleCloudPlatform/django-cloud-deploy#114]
i.e. $ gcloud components install cloud_sql_proxy

**Comment by brianquinlan** [comment]
I don't see this documented anywhere so someone would have to check that this actually works.

**Comment by wangxf123456** [comment]
Previously I tried to install cloud_sql_proxy with gcloud on my Linux workstation but failed with the following message:

```bash
$ gcloud components install cloud_sql_proxy
ERROR: (gcloud.components.install) 
The cloud_sql_proxy component(s) is unavailable through the packaging system 
you are currently using. Please consider using a separate installation 
of the Cloud SDK created through the default mechanism described at: 

https://cloud.google.com/sdk/ 
```
I did not do any further researches to solve this. Now I just found if we install gcloud by "apt-get" or "yum", then we will see this error. If we install gcloud with its installer, then this command works. See https://stackoverflow.com/questions/42697026/install-google-cloud-components-error-from-gcloud-command.

So whether this works depend on how user install gcloud. If they do not have gcloud installed and just follow our instruction, this command works. If they have gcloud pre installed, this might or might not work.

**Comment by brianquinlan** [comment]
Ahhhhh.... that actually makes sense. If the user installed gcloud through a package manager then ideally they should install cloud_sql_proxy the same way...but I see that it isn't packaged for debian.

Not sure what we should do then.
