### ISSUE TITLE
tool_requirements should have unit tests

### ISSUE THREAD

**Issue by brianquinlan** [GoogleCloudPlatform/django-cloud-deploy#198]
These unit tests should test all code paths.

**Comment by enriquejosepadilla** [comment]
Is there much value in creating unit tests when there are already integration tests?

Reasoning behind this is that the logic behind this code is very straightforward, mostly using shutil.which and then handles the if/else. Unit tests will mock that part and just expect that the if else was branched correctly?

**Comment by brianquinlan** [comment]
The integration tests have really poor coverage because they only test one platform and set of installed utilities. Yeah, I'd mock shutil.which to hit all of the branches.
