### ISSUE TITLE
Run presubmit tests on all support platforms i.e. Mac OS X, Linux and Windows

### ISSUE THREAD

**Issue by brianquinlan** [GoogleCloudPlatform/django-cloud-deploy#214]

**Comment by wangxf123456** [comment]
Though Windows is supported on Travis CI, Python on Windows is not supported. See https://travis-ci.community/t/python-support-on-windows/241

I also tried to run test with Travis on WIndows which failed to start ([Link](https://travis-ci.org/GoogleCloudPlatform/django-cloud-deploy/builds/508142669)).
