### ISSUE TITLE
Save whether the project was deployed with GKE or GAE in the project's configuration file

### ISSUE THREAD

**Issue by wangxf123456** [GoogleCloudPlatform/django-cloud-deploy#250]
If the project was deployed with GKE, and then we want to use "update" command to update it, because by default the "update" command uses GAE, it complains that the project cannot be deployed on GAE.

**Comment by enriquejosepadilla** [comment]
which configuration file do you think we should use? Im looking at the app.yaml ?

**Comment by wangxf123456** [comment]
In .config.yaml. It looks like the following:

```
# Generated file, do not edit
django_project_name: Django Project
project_id: django-project123
```

We can just add another attribute for whether this project was previously deployed by GKE or GAE. The code creating this config file is at https://github.com/GoogleCloudPlatform/django-cloud-deploy/blob/master/django_cloud_deploy/workflow/__init__.py#L244
