### ISSUE TITLE
AttributeError:'Namespace' object has no attribute 'backend' during "django-cloud-deploy update"

### ISSUE THREAD

**Issue by brianquinlan** [GoogleCloudPlatform/django-cloud-deploy#258]
I think that `update` is just plain broken:
https://github.com/GoogleCloudPlatform/django-cloud-deploy/blob/master/django_cloud_deploy/cli/update.py#L48

## Issue running command
django-cloud-deploy update

## Environment information

Django Cloud Deploy: [0.1.6]

Platform: [Windows-10.0.17134]

Gcloud Version: [234.0.0]

Cloud SQL Proxy Version: [Cloud SQL Proxy: version 1.13; sha ac834ce67862b7c4ed8bdbe86e664572f820c245 built Tue Oct  9 23:39:16 UTC 2018]

Python Version: [3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)]]

Docker Version: [Docker version 18.09.2, build 6247962]

## Traceback
```.pytb
Traceback (most recent call last):
  File "c:\users\brian\documents\github\django-cloud-deploy\django_cloud_deploy\django_cloud_deploy.py", line 27, in _update
    update.main(args)
  File "c:\users\brian\documents\github\django-cloud-deploy\django_cloud_deploy\cli\update.py", line 48, in main
    console, args.backend):
AttributeError: 'Namespace' object has no attribute 'backend'

```

**Comment by enriquejosepadilla** [comment]
wups, that was due to most recent PR, missed that it was being used there. Our tests didnt pick it up because we call the workflow directly, and dont test the entry point of our code.

**Comment by wangxf123456** [comment]
The e2e test does not call the workflow directly. It calls "update.main()". But in e2e test we provided the "backend" parameter with a SimpleNamespace object, so "update.main()" can still get it.
