### ISSUE TITLE
When opening the web browser a wierd error message is shown

### ISSUE THREAD

**Issue by enriquejosepadilla** [GoogleCloudPlatform/django-cloud-deploy#272]
Your app is running at http://35.203.132.203/.
(venv) epad:~$ [88611:88632:0306/222807.194943:ERROR:browser_process_sub_thread.cc(209)] Waited 5 ms for network service
Opening in existing browser session.

This was deploying to GKE, but i believe it happen as well when using GAE.

**Comment by wangxf123456** [comment]
Looks like this one is from chrome, not from our code.

**Comment by enriquejosepadilla** [comment]
@brianquinlan Do you have any idea how we can surpress the message from webbrowser package? API of webbrowser doesnt seem to be able to, and warnings.filterwarnings doesn't seem able to do it either.
