### ISSUE TITLE
Support newer versionn of urllib3

### ISSUE THREAD

**Issue by AtHeartEngineer** [GoogleCloudPlatform/django-cloud-deploy#310]
django-cloud-deploy 0.1.7 has requirement urllib3==1.23, but you'll have urllib3 1.24.1 which is incompatible.

Maybe `urllib3>=1.23` instead?

**Comment by wangxf123456** [comment]
Thanks for your bug report. Previously we pin urllib3 to 1.23 because of the issue mentioned in https://github.com/requests/requests/issues/4830. Now looks like it is resolved right now.
