### ISSUE TITLE
Cluster creation failed with "Master version "1.9.7-gke.6" is unsupported."

### ISSUE THREAD

**Issue by wangxf123456** [GoogleCloudPlatform/django-cloud-deploy#58]

**Comment by brianquinlan** [comment]
This means that the pip version won't work until we fix this, right? If so, could you make it your highest priority?

Also, is there a way to avoid this happening in the future?

**Comment by wangxf123456** [comment]
Yes the pip version will fail. I tried to avoid this with calling api https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations/getServerConfig to get the default version, but looks like return value of this api is inconsistent with what it really supports.
