### ISSUE TITLE
google-cloud-deploy update requires too much information from the user

### ISSUE THREAD

**Issue by brianquinlan** [GoogleCloudPlatform/django-cloud-deploy#64]
In particular, it requires:
1. the project id
2. the database password
3. the django directory path
4. the django project name

I think that we should only have to prompt for (2) and (4). Maybe we could store (1) and (3) in some sort of configuration file (e.g. google_cloud_config.yaml)

If we use that approach, we should have a big "GENERATED FILE, DO EDIT" text at the top of the file.

**Comment by wangxf123456** [comment]
Do you think it is worthwhile to handle multiple configurations? For example, the functionality below:

$ django-cloud-deploy config list
PROJECT_ID  PROJECT_NAME DJANGO_NAME DIRECTORY ACTIVE
project1           ....                           ...                         ...                   NO
project2           ....                           ...                         ...                   YES

$ django-cloud-deploy update
Update project 1. Only prompt for credentials and database_name.

$ django-cloud-deploy config set project2
$ django-cloud-deploy config list
PROJECT_ID  PROJECT_NAME DJANGO_NAME DIRECTORY ACTIVE
project1           ....                           ...                         ...                   YES
project2           ....                           ...                         ...                   NO

$ django-cloud-deploy update
Update project 2.

$ django-cloud-deploy new
Generate another config

$ django-cloud-deploy config list
PROJECT_ID  PROJECT_NAME DJANGO_NAME DIRECTORY ACTIVE
project1           ....                           ...                         ...                   NO
project2           ....                           ...                         ...                   NO
project3           ....                           ...                         ...                   YES

**Comment by wangxf123456** [comment]
Fixed by #86
