### ISSUE TITLE
tool_requirements.py asks user to install cloud_sql_proxy manually after it is installed by our tool

### ISSUE THREAD

**Issue by wangxf123456** [GoogleCloudPlatform/django-cloud-deploy#67]
Output of the tool:

$ django-cloud-deploy new
Cloud Sql Proxy is required, download? [Y/n]:y
Please install the following requirements:
* Gcloud SDK: Please download Google Cloud SDK from https://cloud.google.com/sdk/docs/downloads-interactive
* Docker: Please download Docker from https://store.docker.com/
* Cloud Sql Proxy: Please download Cloud SQL Proxy from https://cloud.google.com/sql/docs/mysql/sql-proxy

**Comment by enriquejosepadilla** [comment]
It also asked participants to redownload dependencies they had downloaded in previous steps.
