### ISSUE TITLE
Remove the need to reauthenticate during the process if user encounters issues and needs to redeploy/reupdate.

### ISSUE THREAD

**Issue by enriquejosepadilla** [GoogleCloudPlatform/django-cloud-deploy#76]
Focusing ticket to remove reauth after having authenticated already.

**Comment by enriquejosepadilla** [comment]
If the one monolithic command fails, you have to start over, which is a lengthy process.

**Comment by enriquejosepadilla** [comment]
@wangxf123456 Simplified this ticket to specifically not have to reauth.

**Comment by wangxf123456** [comment]
Fixed in #125
