### ISSUE TITLE
Progress Bar for longer steps

### ISSUE THREAD

**Issue by enriquejosepadilla** [GoogleCloudPlatform/django-cloud-deploy#99]
For enabling services we can chunk it up for each service being enabled,

Not sure about the kube deployment one @wangxf123456 ?

**Comment by wangxf123456** [comment]
Kube deployment contains the following steps:

- Create a cluster (~5 minutes)
- Build, push docker image (2-10 minutes depending on user's network speed)
- Deploy the app (<1 minute)
- Wait for deployment to be ready (~2 minutes)
- Wait for service to be ready (~1 minute)

We might be able to give a weight for each step.
